### ISSUE TITLE
Error when using with Browserify

### ISSUE THREAD

**Issue by ucodi** [meltingice/psd.js#116]
When I try to use psd.js with Browserify, using the browser example 
```
var PSD = require('psd');

// Load from URL
PSD.fromURL("/path/to/file.psd").then(function(psd) {
  document.getElementById('ImageContainer').appendChild(psd.image.toPng());
});
```
I have an error

```
browserify main.js > dist/bundle.js
Error: Parsing file /home/david/Documents/psdify/node_modules/psd/lib/psd.coffee: Unexpected character '#' (1:0)
    at Deps.parseDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:481:28)
    at getDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:414:40)
    at /usr/lib/node_modules/browserify/node_modules/module-deps/index.js:398:32
    at ConcatStream.<anonymous> (/usr/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:570:10)
```
Did I make a mistake?

**Comment by fabulousduck** [comment]
Hey @ucodi.

Sorry for the late response.

It seems that Browserify is failing to compile the module properly.

The reason for this is that PSD.js is written in coffeescript and Browserify cannot compile that by default, hence the parse error.

You might have to look into something like [coffeeify](https://github.com/jnordberg/coffeeify) to have the PSD.js node module compile.


Regards, Duck.

**Comment by ucodi** [comment]
Hello @fabulousduck.

I tried coffeeify but same error.
Do you know a way to use psd.js in browser side that work ?

**Comment by fabulousduck** [comment]
Hey @ucodi.

This does seems to be a problem parsing the coffeescript with Browserify.

I cannot however help in fixing this as my knowledge on using browserify is extremely limited.
I would recommend you google around a little bit to see if anyone else has had issues with parsing coffeescript in the past and see if they have a solution for your problem.

If, however you are able to run other node modules written in coffeescript and not PSD.js, maybe @meltingice can help you with this as he probably knows a lot more on the subject than i do.

Regards, Duck.

**Comment by HaiNV266** [comment]
I 'm also having same error. Can anyone help me ?
