### ISSUE TITLE
FromFile function broken

### ISSUE THREAD

**Issue by fabulousduck** [meltingice/psd.js#118]
When parsing a PSD file with the `fromFile()` function i get the following error
```
/Users/ryanvlaming/js/npm-module-boilerplate/node_modules/psd/lib/psd/nodes/root.coffee:27
      layer.right = psd.header.width;
                              ^

TypeError: Cannot read property 'width' of null
  at Function.module.exports.Root.layerForPsd (/Users/ryanvlaming/js/npm-module-boilerplate/node_modules/psd/lib/psd/nodes/root.coffee:13:29)
  at new Root (/Users/ryanvlaming/js/npm-module-boilerplate/node_modules/psd/lib/psd/nodes/root.coffee:20:16)
  at PSD.module.exports.PSD.tree (/Users/ryanvlaming/js/npm-module-boilerplate/node_modules/psd/lib/psd.coffee:92:16)
  at convert (/Users/ryanvlaming/js/npm-module-boilerplate/lib/PSDToHTML.js:13:16)
  at Object.<anonymous> (/Users/ryanvlaming/js/npm-module-boilerplate/examples/example1.js:3:9)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3```


I am not sure as to why this is happening as the header of this file is correct and in the correct address.

This has been tested with 2 different PSD files to confirm the issue does not lie with the files themselves.

It als appears to be an isolated issue since parsing the files with the `open` function works just fine.

**Comment by ericguzman** [comment]
Just ran into this same issue, but it doesn't seem to be a bug. In case you still have this issue or anyone else runs into this:

According to documentation, you must call parse() after fromFile().
