### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by gamegee** [meltingice/psd.js#129]
I got this error:
```
 RangeError: Maximum call stack size exceeded
    at codeToString (/home/sim/work/yotako/yotako-importer-psd/node_modules/parse-engine-data/lib/parseEngineData.js:29:32)
    at paresr (/home/sim/work/yotako/yotako-importer-psd/node_modules/parse-engine-data/lib/parseEngineData.js:22:25)
    at TextElements.module.exports.TextElements.parse (/home/sim/work/yotako/yotako-importer-psd/node_modules/psd/lib/psd/layer_info/typetool.coffee:37:19)
    at LazyExecute.module.exports.LazyExecute.load (/home/sim/work/yotako/yotako-importer-psd/node_modules/psd/lib/psd/lazy_execute.coffee:83:23)
    at LazyExecute.get (/home/sim/work/yotako/yotako-importer-psd/node_modules/psd/lib/psd/lazy_execute.coffee:66:12)

```

This issue come from `export()` function.
Each of the following examples throw an error
```
psd.tree.export();
node.export();
node.get('typeTool').export();
```

The error come from this line:
```
function codeToString(engineData){
    return String.fromCharCode.apply(null, engineData);
}
```

Maybe this post can help: https://stackoverflow.com/questions/38432611/converting-arraybuffer-to-string-maximum-call-stack-size-exceeded

**Comment by McSodbrenner** [comment]
This code fixed it for me:

**lib/parseEngineData.js (28)**
```
function codeToString(engineData){
    var string = '';
    engineData.forEach(function(el){
        string += String.fromCharCode(el);
    });
    return string;
}
```

Unfortunately I don't know where to fix it in the Coffeescript code.
