### ISSUE TITLE
calling `.toPng` on a `Group` item ?

### ISSUE THREAD

**Issue by littlee** [meltingice/psd.js#173]
when calling `.toPng` on a `Group` item, which has many `Layer`s inside, it throw an Error
```
png.js:12 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at LazyExecute.toBase64 (http://localhost:3000/static/js/0.chunk.js:17719:27)
    at LazyExecute.toPng (http://localhost:3000/static/js/0.chunk.js:17733:22)
    at Group.toPng (http://localhost:3000/static/js/0.chunk.js:16645:31)
    at <anonymous>:1:54
```

Is it possible to export `Group` item to png ?

**Comment by tinypoint** [comment]
Export group is not supported.
