### ISSUE TITLE
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by UILKUNP** [meltingice/psd.js#231]
### Psd File Download
https://github.com/UILKUNP/psd.js-file-error/releases/tag/946.psd

### error code
```js
const PSD = require('psd');
PSD.open("/Users/zalss/Desktop/946.psd").then(function (psd:any) {
    return psd.image.saveAsPng('/Users/zalss/Desktop/946.png');
}).then(function () {
    console.log("Finished!");
});
```
### console
```shell
<--- Last few GCs --->

[16996:0x1048f3000]     8251 ms: Scavenge 1057.8 (1075.2) -> 1047.3 (1078.4) MB, 1.8 / 0.0 ms  (average mu = 0.777, current mu = 0.920) allocation failure 
[16996:0x1048f3000]     8259 ms: Scavenge 1060.8 (1078.4) -> 1050.3 (1081.4) MB, 2.0 / 0.0 ms  (average mu = 0.777, current mu = 0.920) allocation failure 
[16996:0x1048f3000]     8267 ms: Scavenge 1063.8 (1081.4) -> 1053.3 (1084.2) MB, 2.0 / 0.0 ms  (average mu = 0.777, current mu = 0.920) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x10130d6e5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000b1c49 node::Abort() [/usr/local/bin/node]
 3: 0x1000b1daf node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001f60f7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001f6093 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x1003a54f5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x1006f6a1d v8::internal::Runtime_FatalProcessOutOfMemoryInvalidArrayLength(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x100a893d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
[1]    16996 abort      node ./dist/index.js
```

**Comment by MgenGlder** [comment]
👋🏾 Howdy @UILKUNP, I'll have a bit of time this week to try and look at this. It looks like that file is a pretty large one at 100+ mb's. My initial guess is that you may have to run your node program with more heap memory allocated. Have you tried the `NODE_OPTIONS="--max-old-space-size=2048"` when running your node program?

**Comment by UILKUNP** [comment]
thanks，i have tried again today with `node ./index.js` without any NODE_OPTIONS, it‘s works，environment probrems maybe

**Comment by MgenGlder** [comment]
@UILKUNP Definitely possible, glad it works 🎉.

**Comment by thang551999** [comment]
how about on browser? I using this lib on browser to parse PSD file (1.3 GB) and have the same ERR:

> Uncaught (in promise) RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at e [as constructor] (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:13046)
    at new e (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:3691)
    at r.parseChannelImage (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:22291)
    at t.parseLayers (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:45650)
    at t.parse (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:45263)
    at t.load (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:47237)
    at t.get (57887f2e0217a8811d4a4d759df94853.1653465566.js:1:47053)
    at r.get (57887f2e0217a8811d4a4d759df94853.1653465566.js:3:91793)
