### ISSUE TITLE
TypeError on saving layer as PNG

### ISSUE THREAD

**Issue by ThomasRedstone** [meltingice/psd.js#64]
I'm getting this error intermittently, when calling `node.layer.image.saveAsPng(imagePath)`:

`TypeError: pxData.copy is not a function at [object Object].Filter._filterNone (/var/task/node_modules/psd/node_modules/pngjs/lib/filter.js:213:16) at [object Object].Filter.filter (/var/task/node_modules/psd/node_modules/pngjs/lib/filter.js:196:27) at [object Object].Packer.pack (/var/task/node_modules/psd/node_modules/pngjs/lib/packer.js:54:23) at [object Object].<anonymous> (/var/task/node_modules/psd/node_modules/pngjs/lib/png.js:68:22) at nextTickCallbackWith0Args (node.js:415:9) at process._tickDomainCallback (node.js:385:13)`

I've logged node.layer.image to the console, and it has always looked reasonable, any suggestions on how to fix, or debug this would be greatly appreciated.

**Comment by ThomasRedstone** [comment]
After a fair bit of investigation, this issue is basically because pxData is an array, and it's being treated as a Buffer.
Updating PNG JS fixes it.

**Comment by kartsims** [comment]
Updating PNGJS didn't work for me... Which version did you update to ?
